### ISSUE TITLE
Initialize never completes on iOS

### ISSUE THREAD

**Issue by nebev** [mbientlab-projects/MetaWearCordova-Plugin#10]
Hey.
Firstly, I think the README might need updating, as from what I can see, all functionality is under `metawear` and not `mbientlab`. I also installed the plugin using `cordova plugin add https://github.com/mbientlab-projects/MetaWearCordova-Plugin` rather than `cordova plugin add http://www.github.com/mbientlab-projects/cordova-plugin-metawear.html` (as the latter results in a 404). I also see that even though I include `Device.js` before any other functionality, it still takes some time for the variable to become available (although this is easily resolved by using `setTimeout`).

More importantly, I cannot seem to get the Metawear to initialize. I have this code:

```
setTimeout(function(){
    console.info("Initialising Metawear");
    console.info(JSON.stringify(metawear));
    console.info(JSON.stringify(metawear.mwdevice));

    var success = function(result){
    console.log("Initialized with status: " + result);
    }

    var failure = function(result){
    console.log("Initialize Error: " + result);
    }
    
    metawear.mwdevice.initialize(success, failure);
}, 5000);
```

I'm using ionic, and other plugins like `cordova-plugin-ble-central` work fine (although I've removed them to ensure no conflicts). My logs look like:

```
8     617037   info     Initialising Metawear
9     617048   info     {"mwdevice":{}}
10    617054   info     {}
11    617061   log      MWDevice.js: initialize
```
The callback for initialize never gets called. I'm using iOS 9.3.2. Other Metawear applications (Swift & Objective-C) seem to have no issues.

I've also tried other methods (like `connect`) which predictably call the error callback (as I imagine things have not been initialized).

**Comment by lgleasain** [comment]
The initialize is no longer needed.  You can simply use the scan,  connect etc. directly.

**Comment by nebev** [comment]
Good to know. I see you've updated the README to reflect this. Thank you!

**Comment by lgleasain** [comment]
This is a work in progress,  so let me know if there are any features that you would like to see.

**Comment by nebev** [comment]
@lgleasain For me, there are 3 main improvements that I would love:

* Being able to start, stop and read the Step Counter with the BMI160
* Being able to read the battery level for the devices
* Being able to connect to _multiple_ devices simultaneously

Would you like me to create separate Github issues for these?

**Comment by lgleasain** [comment]
The first two are pretty straight forward and are things that I can probably have done in the next week or two.  The last one will take a bit more time to do.  Yes,  if you could create issues for that it would be awesome!   What kind of application are you trying to create?

**Comment by nebev** [comment]
Great. Thank you. Done. The application is a medical application.
